export enum EOnboardingState {
  CHECK_ACCOUNT = 'CHECK_ACCOUNT',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  THROW_ERROR = 'THROW_ERROR',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  CANCEL_VERIFICATION = 'CANCEL_VERIFICATION',
  PASSWORD_FILLED = 'PASSWORD_FILLED',
  PROFILE_FILLED = 'PROFILE_FILLED',
}
