name: Continous Deployment for SSO service

on:
  push:
    paths:
      - 'apps/sso-service/**'
      - 'Dockerfile.sso'
      - 'libs/**'
      - '.github/workflows/ci.sso.yml'
      - '.github/workflows/cd.sso.yml'
    branches: [main]

jobs:
  build-image:
    name: Build and push image
    runs-on: ubuntu-latest
    environment: dev
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push docker
        run: |
          export IMAGE_NAME=huskytechlab/media-sso-service:$GITHUB_SHA
          docker build -t $IMAGE_NAME -f Dockerfile.sso .
          docker tag $IMAGE_NAME huskytechlab/media-sso-service:latest
          docker push $IMAGE_NAME
          docker push huskytechlab/media-sso-service:latest
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   env:
      #     REPOSITORY_NAME: ${{ github.event.repository.name }}
      #   with:
      #     images: huskytechlab/social-media
      #     tags: |
      #       type=sha,prefix=${{ env.REPOSITORY_NAME }}-sso-
      #       type=raw,value=${{ env.REPOSITORY_NAME }}-sso-latest

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: Dockerfile.sso
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
