name: Continous Integration for SSO service

on:
  push:
    paths:
      - 'apps/sso-service/**'
      - 'Dockerfile.sso'
      - 'libs/**'
      - '.github/workflows/ci.sso.yml'
      - '.github/workflows/cd.sso.yml'
    branches: [main]

jobs:
  build-image:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        with:
          images: huskytechlab
          tags: |
            type=sha,prefix=${{ env.REPOSITORY_NAME }}-sso-
            type=raw,value=${{ env.REPOSITORY_NAME }}-sso-latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.sso
          push: true
          tags: ${{ steps.meta.outputs.tags }}
